### PR TITLE
Iec2023113 task2

### PR DESCRIPTION
**Pull request by GskCoder**

### CODE REVIEW

**Comment by kushal7201** [comment]
@GskCoder The screenshot one attached Does'nt match with the Task instructions

**Comment by kushal7201** [comment]
@GskCoder  attach the screenshot 1 showing all three initial commits.

**Comment by GskCoder** [comment]
Sir the Screenshot 1 is in Task 1 folder but i will atch here too

**Comment by GskCoder** [comment]
THE screenshot 2 contains all three initial commits

**Comment by GskCoder** [comment]
Sir i havent taken screenshot 1 can i create a new pull request

**Comment by kushal7201** [comment]
yes

**Pull request closed without merging**
